[General]
loglevel = warning
show-error-page = true
test-timeout = 2
internet-test-url = http://www.feishu.cn
proxy-test-url = http://1.1.1.1/generate_204
exclude-simple-hostnames = true
dns-server = system, 223.5.5.5, 119.29.29.29
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
tun-excluded-routes = 255.255.255.255/32, 224.0.0.167/32
ipv6 = false
ipv6-vif = disabled
block-quic = all-proxy
udp-priority = false
wifi-assist = false
allow-wifi-access = true
include-all-networks = true
include-apns = true
include-cellular-services = true
auto-suspend = false
icmp-forwarding = false
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb

[Proxy]

[Proxy Group]
ᴘʀᴏxʏ = select, include-all-proxies = 1, persistent = 1, no-alert = 0, hidden = 0, icon-url = B1::Plants::Sunflower

[Rule]
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/blocked.list,ᴘʀᴏxʏ
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/cn.list,DIRECT
DOMAIN,apps.apple.com,ᴘʀᴏxʏ
DOMAIN-SUFFIX,ls.apple.com,DIRECT
DOMAIN-SUFFIX,store.apple.com,DIRECT
RULE-SET,SYSTEM,ᴘʀᴏxʏ
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/apple.list,ᴘʀᴏxʏ
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,ᴘʀᴏxʏ,dns-failed
