[General]
ipv6 = false
ipv6-vif = disabled
block-quic = all-proxy
udp-priority = true
test-timeout = 5
internet-test-url = http://www.feishu.cn
proxy-test-url = http://1.1.1.1/generate_204
exclude-simple-hostnames = true
dns-server = system, 223.5.5.5, 119.29.29.29
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
tun-excluded-routes = 255.255.255.255/32
allow-wifi-access = true
allow-hotspot-access = true
include-all-networks = true
wifi-access-http-port = 20216
wifi-access-socks5-port = 20125
compatibility-mode = 1

[Proxy]

[Proxy Group]
ᴘʀᴏxʏ = select, include-all-proxies = 1, persistent = 1, no-alert = 0, hidden = 0, icon-url = B1::Animals::Pet Commands Follow

[Rule]
IP-CIDR,0.0.0.0/32,REJECT,no-resolve
RULE-SET,SYSTEM,ᴘʀᴏxʏ
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/proxy.list,ᴘʀᴏxʏ
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Sakimmoe/Surge-Config/main/Rule/apple.list,DIRECT
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,ᴘʀᴏxʏ,dns-failed

[MITM]
skip-server-cert-verify = true
h2 = true
