# 融合自: gist 官方配置 + https://github.com/EAlyce/conf
# 分流: 国内直连 / 国外代理

[General]
loglevel = warning
show-error-page = false
auto-suspend = false
icmp-forwarding = false
include-all-networks = true
include-apns = true
include-cellular-services = true
wifi-assist = true
block-quic = all-proxy
ipv6 = false
ipv6-vif = disabled
test-timeout = 2
internet-test-url = http://www.feishu.cn
proxy-test-url = http://1.1.1.1/generate_204
exclude-simple-hostnames = true
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, localhost, *.local
dns-server = 223.5.5.5, 114.114.114.114
tun-excluded-routes = 255.255.255.255/32, 224.0.0.167/32
udp-priority = false
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb

[Proxy]
# 替换成你的 Snell 节点信息
Snell = snell, 服务器IP, 26216, psk=密码, version=6, reuse=true, ecn=true, tfo=true

[Proxy Group]
ᴘʀᴏxʏ = select, include-all-proxies=1, persistent=1, no-alert=0, hidden=0

[Rule]
DOMAIN-KEYWORD,dig.zjurl.cn,REJECT-DROP
DOMAIN-KEYWORD,dig.bdurl.net,REJECT-DROP
DOMAIN-KEYWORD,ads,REJECT-DROP
DOMAIN-KEYWORD,is.snssdk.com,REJECT-DROP
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/blocked.list,ᴘʀᴏxʏ
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/cn.list,DIRECT
DOMAIN,apps.apple.com,ᴘʀᴏxʏ
DOMAIN-SUFFIX,ls.apple.com,DIRECT
DOMAIN-SUFFIX,store.apple.com,DIRECT
RULE-SET,SYSTEM,ᴘʀᴏxʏ
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/apple.list,ᴘʀᴏxʏ
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,ᴘʀᴏxʏ,dns-failed
